# Generated by Django 5.1.2 on 2024-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_movie_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('movies', models.ManyToManyField(related_name='actors', to='blog.movie')),
            ],
        ),
    ]
