# Generated by Django 5.1.2 on 2024-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='actor_pics/'),
        ),
    ]
